/*
 * API Endpoints
 * Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.
 *
 * The version of the OpenAPI document: 2
 * Contact: developers@tremendous.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OrdersGetOrderByIdResponseOrderRewardCustomFieldsInner;
import com.konfigthis.client.model.OrdersGetOrderByIdResponseOrderRewardRecipient;
import com.konfigthis.client.model.OrdersGetOrderByIdResponseOrderRewardValue;
import com.konfigthis.client.model.RewardsListAllRewardsResponseRewardsInnerDelivery;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrdersGetOrderByIdResponseOrderReward
 */
public class OrdersGetOrderByIdResponseOrderRewardTest {
    private final OrdersGetOrderByIdResponseOrderReward model = new OrdersGetOrderByIdResponseOrderReward();

    /**
     * Model tests for OrdersGetOrderByIdResponseOrderReward
     */
    @Test
    public void testOrdersGetOrderByIdResponseOrderReward() {
        // TODO: test OrdersGetOrderByIdResponseOrderReward
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'deliverAt'
     */
    @Test
    public void deliverAtTest() {
        // TODO: test deliverAt
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'delivery'
     */
    @Test
    public void deliveryTest() {
        // TODO: test delivery
    }

}
