/*
 * API Endpoints
 * Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.
 *
 * The version of the OpenAPI document: 2
 * Contact: developers@tremendous.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RewardsListAllRewardsResponseRewardsInnerDelivery
 */
public class RewardsListAllRewardsResponseRewardsInnerDeliveryTest {
    private final RewardsListAllRewardsResponseRewardsInnerDelivery model = new RewardsListAllRewardsResponseRewardsInnerDelivery();

    /**
     * Model tests for RewardsListAllRewardsResponseRewardsInnerDelivery
     */
    @Test
    public void testRewardsListAllRewardsResponseRewardsInnerDelivery() {
        // TODO: test RewardsListAllRewardsResponseRewardsInnerDelivery
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
