/*
 * API Endpoints
 * Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.
 *
 * The version of the OpenAPI document: 2
 * Contact: developers@tremendous.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhooksGetDetails200ResponseWebhook
 */
public class WebhooksGetDetails200ResponseWebhookTest {
    private final WebhooksGetDetails200ResponseWebhook model = new WebhooksGetDetails200ResponseWebhook();

    /**
     * Model tests for WebhooksGetDetails200ResponseWebhook
     */
    @Test
    public void testWebhooksGetDetails200ResponseWebhook() {
        // TODO: test WebhooksGetDetails200ResponseWebhook
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'privateKey'
     */
    @Test
    public void privateKeyTest() {
        // TODO: test privateKey
    }

}
