/*
 * API Endpoints
 * Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.
 *
 * The version of the OpenAPI document: 2
 * Contact: developers@tremendous.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BalanceTransactionsListAllResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceTransactionsApi
 */
@Disabled
public class BalanceTransactionsApiTest {

    private static BalanceTransactionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BalanceTransactionsApi(apiClient);
    }

    /**
     * List balance transactions
     *
     * Fetch a list of all balance transactions on your account. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        String createdAtGte = null;
        String createdAtLte = null;
        BalanceTransactionsListAllResponse response = api.listAll()
                .offset(offset)
                .limit(limit)
                .createdAtGte(createdAtGte)
                .createdAtLte(createdAtLte)
                .execute();
        // TODO: test validations
    }

}
